version: "3.3"

networks:
  busyevents:
    driver: bridge

services:

  localstack:
    image: localstack/localstack
    environment:
      - KINESIS_LATENCY=0
    networks:
      - busyevents
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
