version: "3.3"

services:

  kinesis:
    image: dlsniper/kinesalite:latest
    ports:
      - 4567:4501

  dynamodb:
    image: dlsniper/dynalite:latest
    ports:
      - 4567:4502

  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - 9324:4503
